package com.goku.mapper;

import com.goku.model.sysUserInfo;

public interface sysUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_info
     *
     * @mbg.generated
     */
    int insert(sysUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_info
     *
     * @mbg.generated
     */
    int insertSelective(sysUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_info
     *
     * @mbg.generated
     */
    sysUserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(sysUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(sysUserInfo record);
}